site_name: NMCP Yemen Info System Docs
# site_url: https://hamza-ye.github.io/mass-pro-docs/
site_author: Hamza
repo_name: MassPro-NMCPYE Docs
repo_url: https://github.com/MassPro-NMCPYE/mass-pro-docs
edit_uri: edit/main/docs/
theme:
  # name: readthedocs
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    # - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/orgs/MassPro-NMCPYE/discussions

markdown_extensions:
  - tables
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md
  - 2. System Overview: system-overview.md
  - 3. Architecture: architecture.md
  - 4. Data Management: data-management.md
  - 5. Database Schema: database-schema.md
  - 6. User Management: user-management.md
  - 7. Interoperability and Standards: interoperability-and-standards.md
  - 8. Security: security.md
  - 9. User Interface: user-interface.md
  - 10. Workflow Management: workflow-management.md
  - 11. Implementation Details: implementation-details.md
  - 12. Future Enhancements: future-enhancements.md
  - 13. Diagrams and Visuals: diagrams-and-visuals.md

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
